version: '3.8'

services:
  # Frontend (Client)
  client:
    build:
      context: ./client-data-sme
      dockerfile: Dockerfile
    container_name: sme_client
    ports:
      - "80:80"
    env_file:
      - ./client-data-sme/.env
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    networks:
      - sme_network

  # Backend (API Gateway)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sme_client_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - sme_network

networks:
  sme_network:
    driver: bridge